Generate ATD out of JSON Scheme
  $ jsonschema2atd ./mocks/simple_jsonschema.json
  (* Generated by jsonschema2atd from simple_jsonschema.json *)
  type json <ocaml module="Yojson.Basic" t="t"> = abstract
  type int64 = int <ocaml repr="int64">
  
  type product = {
    ?productId <doc text="The unique identifier for a product">: int option;
  }
Generate ATD out of JSON Scheme with --format attribute
  $ jsonschema2atd --format jsonschema ./mocks/simple_jsonschema.json
  (* Generated by jsonschema2atd from simple_jsonschema.json *)
  type json <ocaml module="Yojson.Basic" t="t"> = abstract
  type int64 = int <ocaml repr="int64">
  
  type product = {
    ?productId <doc text="The unique identifier for a product">: int option;
  }
Generate ATD out of JSON Scheme with -f attribute
  $ jsonschema2atd -f jsonschema ./mocks/simple_jsonschema.json
  (* Generated by jsonschema2atd from simple_jsonschema.json *)
  type json <ocaml module="Yojson.Basic" t="t"> = abstract
  type int64 = int <ocaml repr="int64">
  
  type product = {
    ?productId <doc text="The unique identifier for a product">: int option;
  }
Generate ATD out of OpenAPI doc with --format attribute
  $ jsonschema2atd --format openapi ./mocks/simple_openapi.json
  (* Generated by jsonschema2atd from simple_openapi.json *)
  type json <ocaml module="Yojson.Basic" t="t"> = abstract
  type int64 = int <ocaml repr="int64">
  
  type product = {
    ?productId <doc text="The unique identifier for a product">: int option;
  }
Generate ATD out of OpenAPI doc with -f attribute
  $ jsonschema2atd -f openapi ./mocks/simple_openapi.json
  (* Generated by jsonschema2atd from simple_openapi.json *)
  type json <ocaml module="Yojson.Basic" t="t"> = abstract
  type int64 = int <ocaml repr="int64">
  
  type product = {
    ?productId <doc text="The unique identifier for a product">: int option;
  }

Generate ATD out of JSON Schema that contains defs
  $ jsonschema2atd --format=jsonschema ./mocks/jsonchema_defs.json
  (* Generated by jsonschema2atd from jsonchema_defs.json *)
  type json <ocaml module="Yojson.Basic" t="t"> = abstract
  type int64 = int <ocaml repr="int64">
  
  type name = string
  
  type root = {
    first_name : name;
    last_name : name;
  }

Generate ATD out of JSON Schema that contains definitions (legacy support)
  $ jsonschema2atd --format=jsonschema ./mocks/jsonchema_definitions.json
  (* Generated by jsonschema2atd from jsonchema_definitions.json *)
  type json <ocaml module="Yojson.Basic" t="t"> = abstract
  type int64 = int <ocaml repr="int64">
  
  type name = string
  
  type root = {
    first_name : name;
    last_name : name;
  }

Generate ATD out of JSON Schema that uses references
  $ jsonschema2atd --format=jsonschema ./mocks/jsonschema_refs.json
  (* Generated by jsonschema2atd from jsonschema_refs.json *)
  type json <ocaml module="Yojson.Basic" t="t"> = abstract
  type int64 = int <ocaml repr="int64">
  
  type root = {
    first_name : string;
    last_name : string;
    shipping_address : json (* /schemas/address *);
    billing_address : json (* /schemas/address *);
    ?aa : json (* https://example.com/schemas/address *) option;
    ?bb : json (* http://example.com/schemas/address *) option;
    ?cc : json (* http://example.com/schemas#/definitions/address *) option;
    ?dd : json (* http://example.com/schemas#/definitions/address *) option;
    ?ee : address option;
    ?ff : address option;
  }

Generate ATD out of JSON Schema that uses references
  $ jsonschema2atd --format=jsonschema --only-matching nothing ./mocks/jsonschema_refs.json
  (* Generated by jsonschema2atd from jsonschema_refs.json *)
  type json <ocaml module="Yojson.Basic" t="t"> = abstract
  type int64 = int <ocaml repr="int64">
  

Generate ATD out of JSON Schema that uses enums
  $ jsonschema2atd --format=jsonschema ./mocks/jsonschema_enums.json
  (* Generated by jsonschema2atd from jsonschema_enums.json *)
  type json <ocaml module="Yojson.Basic" t="t"> = abstract
  type int64 = int <ocaml repr="int64">
  
  type rootMyProperty = [
    | Foo <json name="foo">
    | Bar <json name="bar">
  ]
  
  type rootMyPropertyInt = int
  
  type rootMyPropertyNumber = float
  
  type rootMyPropertyBool = bool
  
  type root = {
    myProperty : rootMyProperty;
    ?myPropertyInt : rootMyPropertyInt option;
    ?myPropertyNumber : rootMyPropertyNumber option;
    ?myPropertyBool : rootMyPropertyBool option;
  }
